#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /
    controller: App\Controller\AccueilController::index

voyages:
    path: /voyages
    controller: App\Controller\VoyagesController::index    

voyages.sort: 
    path : /voyage/tri/{champ}/{ordre}
    controller : App\Controller\VoyagesController::sort