#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /
    controller: App\Controller\AcceuilController::index

voyages:
    path: /voyages
    controller: App\Controller\VoyagesController::index 